config/routes.rb
Rails.application.routes.draw do

  resources :invoice_lines
  resources :invoices
# You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/autocomplete"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/activity_stream"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/datamaps"
  get "miscellaneous/social_buttons"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/pdf_viewer"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/spinners_usage"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/text_spinners"
  get "miscellaneous/truncate"
  get "miscellaneous/password_meter"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/helper_classes"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/invoice_line.rb
class InvoiceLine < ApplicationRecord
  belongs_to :invoice
end

app/controllers/invoice_lines_controller.rb
class InvoiceLinesController < ApplicationController
  before_action :set_invoice_line, only: %i[ show edit update destroy ]

  # GET /invoice_lines or /invoice_lines.json
  def index
    @invoice_lines = InvoiceLine.all
  end

  # GET /invoice_lines/1 or /invoice_lines/1.json
  def show
  end

  # GET /invoice_lines/new
  def new
    @invoice_line = InvoiceLine.new
  end

  # GET /invoice_lines/1/edit
  def edit
  end

  # POST /invoice_lines or /invoice_lines.json
  def create
    @invoice_line = InvoiceLine.new(invoice_line_params)

    respond_to do |format|
      if @invoice_line.save
        format.html { redirect_to invoice_line_url(@invoice_line), notice: "Invoice line was successfully created." }
        format.json { render :show, status: :created, location: @invoice_line }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_lines/1 or /invoice_lines/1.json
  def update
    respond_to do |format|
      if @invoice_line.update(invoice_line_params)
        format.html { redirect_to invoice_line_url(@invoice_line), notice: "Invoice line was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice_line }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_lines/1 or /invoice_lines/1.json
  def destroy
    @invoice_line.destroy

    respond_to do |format|
      format.html { redirect_to invoice_lines_url, notice: "Invoice line was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_line
      @invoice_line = InvoiceLine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_line_params
      params.require(:invoice_line).permit(:charge_type, :item_no, :description, :quantity, :unit_of_measure, :unit_price, :amount, :invoice_id)
    end
end

app/helpers/invoice_lines_helper.rb
module InvoiceLinesHelper
end

app/views/invoice_lines/_form.html.erb
<%= form_with(model: invoice_line, local: true) do |form| %>
  <% if invoice_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_line.errors.count, "error") %> prohibited this invoice_line from being saved:</h2>

      <ul>
        <% invoice_line.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :charge_type %>
    <%= form.text_area :charge_type %>
  </div>

  <div class="field">
    <%= form.label :item_no %>
    <%= form.text_area :item_no %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :unit_of_measure %>
    <%= form.text_area :unit_of_measure %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.text_field :unit_price %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.text_field :invoice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_lines/edit.html.erb
<h1>Editing Invoice Line</h1>

<%= render 'form', invoice_line: @invoice_line %>

<%= link_to 'Show', @invoice_line %> |
<%= link_to 'Back', invoice_lines_path %>

app/views/invoice_lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Lines</h1>

<table>
  <thead>
    <tr>
      <th>Charge type</th>
      <th>Item no</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Unit of measure</th>
      <th>Unit price</th>
      <th>Amount</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_lines.each do |invoice_line| %>
      <tr>
        <td><%= invoice_line.charge_type %></td>
        <td><%= invoice_line.item_no %></td>
        <td><%= invoice_line.description %></td>
        <td><%= invoice_line.quantity %></td>
        <td><%= invoice_line.unit_of_measure %></td>
        <td><%= invoice_line.unit_price %></td>
        <td><%= invoice_line.amount %></td>
        <td><%= invoice_line.invoice_id %></td>
        <td><%= link_to 'Show', invoice_line %></td>
        <td><%= link_to 'Edit', edit_invoice_line_path(invoice_line) %></td>
        <td><%= link_to 'Destroy', invoice_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Line', new_invoice_line_path %>

app/views/invoice_lines/new.html.erb
<h1>New Invoice Line</h1>

<%= render 'form', invoice_line: @invoice_line %>

<%= link_to 'Back', invoice_lines_path %>

app/views/invoice_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Charge type:</strong>
  <%= @invoice_line.charge_type %>
</p>

<p>
  <strong>Item no:</strong>
  <%= @invoice_line.item_no %>
</p>

<p>
  <strong>Description:</strong>
  <%= @invoice_line.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @invoice_line.quantity %>
</p>

<p>
  <strong>Unit of measure:</strong>
  <%= @invoice_line.unit_of_measure %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @invoice_line.unit_price %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invoice_line.amount %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @invoice_line.invoice_id %>
</p>

<%= link_to 'Edit', edit_invoice_line_path(@invoice_line) %> |
<%= link_to 'Back', invoice_lines_path %>